project:
  type: website

website:
  title: "Empowering Data Vision: a Self-Paced Introduction to the Convergence of AI and Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: course.qmd
        text: Modules

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true