# Intro to Copilot

Copilot in VS Code provides programmers with the tools to get AI code suggestions, and get AI assistance to generate entire projects or patches to code. Copilot also helps with answering questions about the codebase, the programming language in general, or about VS Code. You will need to have a github account to be able to get AI assistance with VS Code. Once you have a github account, please follow the instructions on this [documentation page](https://code.visualstudio.com/docs/copilot/setup) to setup copilot. These setup steps are undergoing changes so we are pointing you to them instead of describing them ourselves to ensure that you have the most up-to-date documentation. The instructions on the page describe hovering over an icon and clicking -- an interaction that is inaccessible to screen reader users. We recommend searching for "ai" or "copilot" on the command pallett and finding either the "use AI chat features" or "setup copilot" option. Please attend office hours or post on the discussion board if you are running into issues. At a high-level, setup steps for copilot involve:
* Logging into github.
* signing up for the free copilot plan.
* getting back to the VS Code screen from the browser to make sure that the editor receives confirmation of your actions on the browser.

In the next chapters, I will describe how to use copilot with a screen reader to review and accept code suggestions, ask copilot questions about your code, and accessibly go through edits made by copilot and accept or reject them. Copilot extensiely uses auditory feedback along with the accesible view (alt+f2). I will list audio signals corresponding to the cues that will be played as you may use copilot; I highly encourage you to review these using the functionality explained in the VS Code module as you are reading through the content.